### ISSUE TITLE
Install using VendettaManager

### ISSUE THREAD

**Issue by enderprism** [pyoncord/Bunny#4]
hi! i'm a non-rooted android user and i have no idea how to install this fork with VendettaManager :/

**Comment by amsryq** [comment]
Hello! Unfortunately, Bunny doesn't have any proper installation method at the moment. I recommend sticking to Vendetta for now or checking out other forks

**Comment by RWCoding58** [comment]
It'd probably be useful to add this information to the README since it currently lists VendettaManager (along with some other methods which I don't think are supported yet) in the ["Installing" section](https://github.com/pyoncord/Bunny?tab=readme-ov-file#installing), appearing as if it is supported.

**Comment by amsryq** [comment]
I have updated a proper installation guide in the README

**Comment by RWCoding58** [comment]
yipee
