### ISSUE TITLE
cloud sync in bunny

### ISSUE THREAD

**Issue by Celestemysterios** [pyoncord/Bunny#49]
it would work smth like nexpids cloud sync for vendetta but directly in the client

**Comment by amsryq** [comment]
This is not a place to request plugins, and there aren't any yet

**Comment by borealis999** [comment]
If something can be accomplished with a current Vendetta plugin my opinion is there is no reason to develop a native version.

**Comment by Celestemysterios** [comment]
> If something can be accomplished with a current Vendetta plugin my opinion is there is no reason to develop a native version. 

i was just saying just for convenience
so that way you dont have to hunt down the link to download the plugin
or if someone is already in 100/200 servers and cant join the bunny server

**Comment by borealis999** [comment]
> > If something can be accomplished with a current Vendetta plugin my opinion is there is no reason to develop a native version.
> 
> i was just saying just for convenience so that way you dont have to hunt down the link to download the plugin or if someone is already in 100/200 servers and cant join the bunny server

Minor conveniences are a waste of development time. 

You're saying that hours of development time should be invested so that you can be lazy and not need to figure out which of the 100 or 200 Discord servers you can leave to join the Bunny server. Or so that you can be lazy and not have to spend ten, fifteen minutes to find the link. 

I think those hours of development time should be put into something more worthwhile that can't be accomplished by simply installing an extension and not being lazy.
