### ISSUE TITLE
[Question] `bunny-build-info.version` hash generation

### ISSUE THREAD

**Issue by mangkoran** [pyoncord/Bunny#57]
Hi dev. First of all thank you for all of your hard works on Bunny to keep the modding scene alive 🙏

I have a question regarding `bunny-build-info.version`. Based on response on the server, the `bunny-build-info.version` that shown in Setting is generated during build time by the following lines:

https://github.com/pyoncord/Bunny/blob/e19e89ca12f292e9e2d3244563d2290d6e0bcc07/scripts/build.mjs#L77
https://github.com/pyoncord/Bunny/blob/bf21e98c5be15b051eca73363b6e71dddfe46e7a/scripts/build.mjs#L119

May I ask the reason to generate the version hash on build time? I found it's a bit hard to track which Bunny version I'm on as the hash is *just* a hash that AFAIK doesn't refer to anything. One need to dig into the build file of such version like this one for [`e9d80c7-main`](https://raw.githubusercontent.com/pyoncord/bunny-builds/70d5be9e941f6d2f897aa5ab84e4f5ca829b3a6d/bunny.js). The hash will also change whenever we run the build script with the *same* commit.

What do you think if we update the `bunny-build-info.version` to be the commit hash the build is using? E.g. for the above version, the string would be `e19e89c-main` to refer [the commit](https://github.com/pyoncord/Bunny/commit/e19e89ca12f292e9e2d3244563d2290d6e0bcc07) it was built on. This way anyone could find the build/commit of Bunny they are using which might help for troubleshooting and development.

I'm happy to create a PR for this.

**Comment by amsryq** [comment]
This is indeed something I overlooked as I ported the build scripts from a personal project. The version hashes are mistakenly generated at random at all times, instead of only for local builds previously. The hashes are purposely random for local builds so I can ensure that my device always loads the latest build

You're welcome to fix it by only making it random for local builds, and fetch the latest commit hash otherwise

**Comment by mangkoran** [comment]
Thank you for the answer and @Rico040 for the quick fix!
