### ISSUE TITLE
bunny cold start takes 2-3 times longer than stock discord

### ISSUE THREAD

**Issue by o800** [pyoncord/Bunny#62]
after noticicing a large increase in cold start launch time, i tested both stock discord and bunny (with safe mode enabled to prevent any plugins messing with the results) and found that stock discord averaged around 2.1 seconds for first cached render and 2.5 seconds TTI, while bunny averaged around 6.6 seconds for first cahced render and 6.9 seconds TTI.

**Comment by o800** [comment]
I realise I have not provided enough details, if any more details are needed, let me know

**Comment by amsryq** [comment]
Bunny starts slower (especially on Android) mostly because it has to initialize *all* JS modules in advance (which Discord does lazily). Without doing that, we wouldn't know which modules to patch or to use. I have been working on improving this by "caching" modules we need, and it has been available on https://github.com/pyoncord/Bunny/tree/dev, making start-up slightly faster after the first boot of the Discord version. There's nothing can be done for cold start, unfortunately.
