### ISSUE TITLE
bug: Wrong timezone shown

### ISSUE THREAD

**Issue by AlexanderAlexis01** [pyoncord/Bunny#94]
**Describe the bug**
When on messages and server, it shows the wrong timezonez same for the timestampa

**To Reproduce**
1. Go to 'messages/a server'
2. See a message.
3. Time zone is incorrect.
4. thats the error.

**Expected behavior**
I expected bunny to show me my correct timesone, this issue has been happening on the last two times i've updated bunny client.
**Screenshots**
![Screenshot_20241019_074133_io_github_pyoncord_app_MainActivity](https://github.com/user-attachments/assets/826913f2-1448-41d5-951e-fffe78ea88f9)

**Device Information (please complete the following information):**
 - Device: [Honor 90]
 - OS: [MAGIC OS 8.0]
 - Discord Version [251.15
- Bunny Version [e.g e19e89c-main]

**Checklists**
- [ ✓] I understand that this is a bug report and not a place to request new features or plugins
- [ ✓] I understand that this is no place to report bugs produced by a plugin
- [✓ ] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by Rico040** [comment]
what

**Comment by AlexanderAlexis01** [comment]
> what

thats not the italian timezone, we dont have am or pm, this  bug is only on bunny client.

**Comment by Rico040** [comment]
> > what
> 
> thats not the italian timezone, we dont have am or pm, this bug is only on bunny client.

try changing app language

**Comment by AlexanderAlexis01** [comment]
> > > what
> > 
> > 
> > thats not the italian timezone, we dont have am or pm, this bug is only on bunny client.
> 
> try changing app language

i did. several times. even tried to reinstall bunny client.

**Comment by XAlboX** [comment]
The problem comes from the fact that Bunny uses split_config.en.apk while patching which is used for some strings of the app. I had already talked about this problem on the discord server with Pilyx but there is no simple fix 'cause it would mean downloading the apk of every language used by discord (30 languages) and 1 play store account per language is required. If you want to test that this is actually the problem, download the discord apk from ApkMirror, rename it to zip, extract it and rename the file "split_config.it.apk" into "split_config.en.apk", move it in the bunny manager cache folder (/storage/emulated/0/Android/data/io.github.pyoncord.manager/cache/*discordversion*), it will replace the real en file. Reinstall the app though Bunny Manager, it will use cached apks to reinstall and will replace the original en with the new one which is actually the Italian one but renamed.
:D

**Comment by AlexanderAlexis01** [comment]
> The problem comes from the fact that Bunny uses split_config.en.apk while patching which is used for some strings of the app. I had already talked about this problem on the discord server with Pilyx but there is no simple fix 'cause it would mean downloading the apk of every language used by discord (30 languages) and 1 play store account per language is required. If you want to test that this is actually the problem, download the discord apk from ApkMirror, rename it to zip, extract it and rename the file "split_config.it.apk" into "split_config.en.apk", move it in the bunny manager cache folder (/storage/emulated/0/Android/data/io.github.pyoncord.manager/cache/_discordversion_), it will replace the real en file. Reinstall the app though Bunny Manager, it will use cached apks to reinstall and will replace the original en with the new one which is actually the Italian one but renamed. :D

well thanks, i could maybe
contirbute and send the string? so in the future people will also have support for italian?

**Comment by amsryq** [comment]
> The problem comes from the fact that Bunny uses split_config.en.apk

that's not the issue, that will only affect strings on notifications

well, bad news, i can't reproduce this issue
![Screenshot_20241021_180752](https://github.com/user-attachments/assets/f04a28d8-4a38-4d5f-81e4-0137987d1354)

**Comment by XAlboX** [comment]
Same, works on my machine

**Comment by AlexanderAlexis01** [comment]
> > The problem comes from the fact that Bunny uses split_config.en.apk
> 
> that's not the issue, that will only affect strings on notifications
> 
> well, bad news, i can't reproduce this issue ![Screenshot_20241021_180752](https://private-user-images.githubusercontent.com/82711525/378373373-f04a28d8-4a38-4d5f-81e4-0137987d1354.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDY0MzksIm5iZiI6MTcyOTUwNjEzOSwicGF0aCI6Ii84MjcxMTUyNS8zNzgzNzMzNzMtZjA0YTI4ZDgtNGEzOC00ZDVmLTgxZTQtMDEzNzk4N2QxMzU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEwMjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MWRjNTRiNzkwZWVlZmM4ZDJkNWI2ODMzYTU4MzIxMjNlMzQ2ZDdkNDVkOGMyMTdhMjMxMGU0ZTE1Y2I1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._HqNBCTDV73qqDT1IBAwSgldJGvMXffglLntROP__R8)

quite odd. i noticed thst when i change language and back to italian, when someone sends a message it fixes, but aftrr  awhile it comes bsck

**Comment by A1Asriel** [comment]
Same here. I use English (UK), yet it shows 12-hour timestamps on messages instead of 24-hour. The temporary fix is to switch the app language to English (US) and back to UK, but it resets to 12-hour format every time the app is launched.
I have been using Bunny for over half a year, but the issue arose just recently.

**Comment by A1Asriel** [comment]
6f95203dfa5beb3b48a9cc6061e712acd0ca8fb3 seems to have fixed this issue: the timestamps are formatted with accordance to the selected locale now.

**Comment by amsryq** [comment]
weird, they shouldn't be related at all
